### ISSUE TITLE
[Suggestion] model.createAndSave should return Document, and should support nested stuff

### ISSUE THREAD

**Issue by dxgi** [Didas-git/Nekdis#1]
![image](https://user-images.githubusercontent.com/61899298/233821270-f59a65f7-1e92-4f3b-9e54-275c773957bf.png)

I think the model.createAndSave method should at least return the Document.

The model and document should be able to handle nested objects, and array of nested objects.

This is how I implemented mine: 
https://github.com/dxgi/typesafe
https://github.com/dxgi/typesafe/blob/master/src/test/index.ts

**Comment by Didas-git** [comment]
I will think about the benefits of returning the document itself as for now im focusing on finishing the search functionality.

About nested objects, they should already be supported everywhere (even on search), if the problem is whithin the types not showing them, then i made a mistake when i was remaking them.
About supporting array of objects im still searching for possible solutions, curretly the problem is that i havent found a way to implement it properly on RediSearch without some hacky solution (like creating a new key for them)
